spring:
  application:
    name: rest-with-spring-boot-and-kotlin

  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /api-docs
